
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Hero from "./components/Hero/Hero";

const inter = Inter({subsets: ["latin"]});
import { Inter } from "next/font/google";
import { ReactElement } from "react";
import "../app/globals.css";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta name="viewport" content="width-device-width, initial-scale=1"/>
        </head>
        <body className={inter.className}>
        <Hero/>
        {children}
        </body>
        </html>
    );

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }: { children: ReactElement }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
