import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import RecoilWrapper from "./components/RecoilWrapper/RecoilWrapper";
import "../app/globals.css";
import React from "react";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Muse",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <RecoilWrapper>
            {children}
        </RecoilWrapper>
        </body>
        </html>
    );
}
